/* Generated by lynxer --emit-library for libexport_basic.so. Do not edit. */
#ifndef LYNXER_EXPORT_LIBEXPORT_BASIC_SO_H
#define LYNXER_EXPORT_LIBEXPORT_BASIC_SO_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int64_t add(int64_t a0, int64_t a1);
int64_t negate(int64_t a0);
double scale(double a0);
const char* greet(const char* a0);
const uint8_t* echoBytes(const uint8_t* a0, int64_t a0_length);
void sink(int64_t a0);

#ifdef __cplusplus
}
#endif

#endif
