name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Check
        run: make check

      - name: Distcheck
        run: make distcheck

  buildLite:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: ./configure

      - name: Build Lite
        run: make buildLite
