"""Type information for the optional native memory extension."""

from typing import Any

memoryAllocate: Any
memoryAllocateZeroed: Any
memoryReallocate: Any
memoryFree: Any
memorySet: Any
memoryCopy: Any
sizeOf: Any
refGet: Any
refSet: Any
refCreate: Any
nativeCall: Any
ffiCall: Any
ffiCallback: Any
ffiFreeCallback: Any
ffiLoadLibrary: Any
ffiLookup: Any
ffiCloseLibrary: Any
nativeModuleLoad: Any
nativeModuleClose: Any
nativeThreadStart: Any
nativeThreadJoin: Any
nativeThreadIsAlive: Any
nativeThreadStatus: Any
nativeThreadDetach: Any
memoryTypeSize: Any
memoryTypeAlignment: Any
memoryBlockAllocate: Any
memoryBlockView: Any
memoryBlockGet: Any
memoryBlockSet: Any
memoryBlockLength: Any
memoryReadByte: Any
memoryWriteByte: Any
memoryReadInt8: Any
memoryWriteInt8: Any
memoryReadInt16: Any
memoryWriteInt16: Any
memoryReadInt32: Any
memoryWriteInt32: Any
memoryReadInt64: Any
memoryWriteInt64: Any
memoryReadUInt8: Any
memoryWriteUInt8: Any
memoryReadUInt16: Any
memoryWriteUInt16: Any
memoryReadUInt32: Any
memoryWriteUInt32: Any
memoryReadUInt64: Any
memoryWriteUInt64: Any
memoryReadFloat32: Any
memoryWriteFloat32: Any
memoryReadFloat64: Any
memoryWriteFloat64: Any
memoryReadEndian: Any
memoryWriteEndian: Any
memoryStructSize: Any
memoryStructAlignment: Any
memoryStructFieldCount: Any
memoryStructFieldType: Any
memoryStructFieldOffset: Any
memoryStructFieldSize: Any
memoryStructAllocate: Any
memoryStructGet: Any
memoryStructSet: Any