"""Type information for the optional native memory extension."""

from typing import Any

memoryAllocate: Any
memoryAllocateZeroed: Any
memoryReallocate: Any
memoryFree: Any
memorySet: Any
memoryCopy: Any
sizeOf: Any
refGet: Any
refSet: Any
refCreate: Any
nativeCall: Any
ffiCall: Any
ffiCallback: Any
ffiFreeCallback: Any
ffiLoadLibrary: Any
ffiLookup: Any
ffiCloseLibrary: Any
nativeModuleLoad: Any
nativeModuleClose: Any
syscallRead: Any
syscallWrite: Any
syscallOpenAt: Any
syscallClose: Any
syscallReadVector: Any
syscallWriteVector: Any
syscallSeekFile: Any
syscallGetFileStatus: Any
syscallGetFileStatusAt: Any
syscallTruncateFile: Any
syscallSynchronizeFile: Any
syscallSynchronizeFileData: Any
syscallDuplicateFileDescriptor: Any
syscallDuplicateFileDescriptorAt: Any
syscallCreatePipe: Any
syscallControlFileDescriptor: Any
syscallGetDirectoryEntries: Any
syscallReadSymbolicLink: Any
syscallCreateDirectoryAt: Any
syscallRemoveFileAt: Any
syscallRenameFileAt: Any
syscallCreateHardLinkAt: Any
syscallCreateSymbolicLinkAt: Any
syscallChangeFilePermissions: Any
syscallChangeFileDescriptorPermissions: Any
syscallChangeFileOwner: Any
syscallChangeFileDescriptorOwner: Any
syscallMemoryMap: Any
syscallMemoryUnmap: Any
syscallMemoryProtect: Any
syscallMemoryAdvise: Any
syscallMemoryRemap: Any
syscallAdjustProgramBreak: Any
syscallExecuteProgram: Any
syscallExecuteProgramAt: Any
syscallExitProcess: Any
syscallExitAllThreads: Any
syscallWaitForProcess: Any
syscallGetProcessId: Any
syscallGetParentProcessId: Any
syscallSendSignal: Any
syscallCreateThread: Any
syscallGetThreadId: Any
syscallWaitOnMemory: Any
syscallSetThreadIdAddress: Any
syscallSetRobustThreadList: Any
syscallGetRobustThreadList: Any
syscallYieldProcessor: Any
syscallGetClockTime: Any
syscallGetClockResolution: Any
syscallSleep: Any
syscallGetRandomBytes: Any
syscallCreateSocket: Any
syscallCreateSocketPair: Any
syscallBindSocket: Any
syscallListenSocket: Any
syscallAcceptConnection: Any
syscallConnectSocket: Any
syscallSendData: Any
syscallReceiveData: Any
syscallSendMessage: Any
syscallReceiveMessage: Any
syscallShutdownSocket: Any
syscallGetSocketAddress: Any
syscallGetPeerAddress: Any
syscallSetSocketOption: Any
syscallGetSocketOption: Any
syscallPollFileDescriptors: Any
syscallCreateEventPoll: Any
syscallControlEventPoll: Any
syscallWaitForEvents: Any
syscallGetSystemInformation: Any
syscallGetResourceUsage: Any
syscallGetResourceLimit: Any
syscallSetResourceLimit: Any
syscallControlProcess: Any
nativeThreadStart: Any
nativeThreadJoin: Any
nativeThreadIsAlive: Any
nativeThreadStatus: Any
nativeThreadDetach: Any
memoryTypeSize: Any
memoryTypeAlignment: Any
memoryBlockAllocate: Any
memoryBlockView: Any
memoryBlockGet: Any
memoryBlockSet: Any
memoryBlockLength: Any
memoryReadByte: Any
memoryWriteByte: Any
memoryReadInt8: Any
memoryWriteInt8: Any
memoryReadInt16: Any
memoryWriteInt16: Any
memoryReadInt32: Any
memoryWriteInt32: Any
memoryReadInt64: Any
memoryWriteInt64: Any
memoryReadUInt8: Any
memoryWriteUInt8: Any
memoryReadUInt16: Any
memoryWriteUInt16: Any
memoryReadUInt32: Any
memoryWriteUInt32: Any
memoryReadUInt64: Any
memoryWriteUInt64: Any
memoryReadFloat32: Any
memoryWriteFloat32: Any
memoryReadFloat64: Any
memoryWriteFloat64: Any
memoryReadEndian: Any
memoryWriteEndian: Any
memoryStructSize: Any
memoryStructAlignment: Any
memoryStructFieldCount: Any
memoryStructFieldType: Any
memoryStructFieldOffset: Any
memoryStructFieldSize: Any
memoryStructAllocate: Any
memoryStructGet: Any
memoryStructSet: Any